// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLjfKlLR9MC41f5uYm5BIMv0jKrjFHtLU',
    appId: '1:503901677061:web:4c9c16b3007c8577425e6c',
    messagingSenderId: '503901677061',
    projectId: 'grad-project-81216',
    authDomain: 'grad-project-81216.firebaseapp.com',
    storageBucket: 'grad-project-81216.appspot.com',
    measurementId: 'G-6Q35TPTYP9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByPyr7RvltFPXf815hWa77aP1Ax0_1XrY',
    appId: '1:503901677061:android:45631b46419a6b89425e6c',
    messagingSenderId: '503901677061',
    projectId: 'grad-project-81216',
    storageBucket: 'grad-project-81216.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOYcc2EkcNNYQnHarwsgJ2Q9dhruLrAVE',
    appId: '1:503901677061:ios:61f6def2a2291c36425e6c',
    messagingSenderId: '503901677061',
    projectId: 'grad-project-81216',
    storageBucket: 'grad-project-81216.appspot.com',
    iosBundleId: 'com.example.testGrad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOYcc2EkcNNYQnHarwsgJ2Q9dhruLrAVE',
    appId: '1:503901677061:ios:7ad6336404edf7f2425e6c',
    messagingSenderId: '503901677061',
    projectId: 'grad-project-81216',
    storageBucket: 'grad-project-81216.appspot.com',
    iosBundleId: 'com.example.testGrad.RunnerTests',
  );
}
